import Foundation

// MARK: - Cleaned Transcript

/// Result of merging/denoising raw transcript chunks (Stage 1).
/// Multiple raw transcripts → one cleaned transcript (N:1).
struct CleanedTranscript: Identifiable {
    let id: String
    let sessionID: String?
    let sourceTranscriptIDs: [Int64]
    let isContinued: Bool
    let sourceChunkCount: Int
    let cleanedText: String
    let timestamp: Date
    let speakerName: String?
    let durationSeconds: Int
}

// MARK: - Analysis Task Description

/// A task title + prompt pair generated by the analysis LLM.
struct AnalysisTaskDesc {
    let title: String
    let prompt: String
}

// MARK: - Transcript Analysis

/// Semantic analysis of a cleaned transcript (Stage 2).
/// The analysis LLM determines project, priority, people, and writes task prompts.
struct TranscriptAnalysis: Identifiable {
    let id: String
    let cleanedTranscriptID: String
    var priority: String?
    var projectName: String?
    var projectID: String?
    let personNames: [String]
    var tags: [String]
    var summary: String
    let taskDescriptions: [AnalysisTaskDesc]
    let timestamp: Date
}

// MARK: - Pipeline Task Record

/// A real task with execution plan (Stage 3).
/// Created from AnalysisTaskDesc + execution planning (skill, workflow, certainty).
struct PipelineTaskRecord: Identifiable {
    let id: String                    // e.g. "T-AC-048"
    let analysisID: String
    var title: String
    var prompt: String
    var projectID: String?
    var projectName: String?
    var mode: TaskMode
    var status: TaskStatus
    let skillID: String?
    let workflowID: String?
    let workflowSteps: [String]
    let missingConnection: String?
    let pendingQuestion: String?
    let attachmentPaths: [String]     // file paths to context captures (screenshots, images)
    let createdAt: Date
    var startedAt: Date?
    var completedAt: Date?
}

// MARK: - Task Execution Step

/// An individual step logged during task execution (Stage 4).
struct TaskExecutionStep: Identifiable {
    let id: String
    let taskID: String
    let stepIndex: Int
    let description: String
    let status: String               // "completed", "running", "failed"
    let timestamp: Date
    let output: String?
}
